stages:
  - build
  - deploy
  - test

build-server-image:
  stage: build
  script:
    - cd server
    - docker build -t cs590-final-group-5-server .
    - cd ..

build-ui-image:
  stage: build
  script:
    - cd ui
    - docker build -t cs590-final-group-5-ui .
    - cd ..

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/db-deployment.yaml
    - kubectl apply -f k8s/db-service.yaml
    - kubectl apply -f k8s/server-deployment.yaml
    - kubectl apply -f k8s/server-service.yaml
    - kubectl apply -f k8s/ui-deployment.yaml
    - kubectl apply -f k8s/ui-service.yaml

setup-and-test:
  stage: test
  script:
    - kubectl port-forward service/db 27017:27017 &
    - PORT_FORWARD_PID=$!
    - sleep 10 # Give enough time for the port-forward to establish
    - cd server
    - /opt/homebrew/bin/npm install
    - npm run setup 
    - cd ..
    - npm install 
    - npx playwright test
    # Ensure success status from playwright test
    - TEST_RESULT=$?
    - kill $PORT_FORWARD_PID || true  # Ignore errors from kill command
    - (exit $TEST_RESULT)  # Exit the script with the result of Playwright tests