build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building application..."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - echo "Deploying application..."

e2e-test-job:   # This job runs in the test stage.
  stage: test 
  script:
    - echo "Running E2E tests..."
    - npx playwright test --project=chromium
