stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
    - echo "Building application..."
    - cd server
    - npm install && npm run build
    - cd ../ui
    - npm install && npm run build
    - cd ..

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - cd server
    - docker build -t cs590-group-5-server .
    - cd ../ui
    - docker build -t cs590-group-5-ui
    - cd ..
    - kubectl delete -f k8s/ --ignore-not-found=true
    - kubectl apply -f k8s/

e2e-test-job:
  stage: test
  rules:
    - when: manual
  script:
    - echo "Running E2E tests..."
    - npx playwright test --project=chromium
