stages:
  - build_server
  - build_ui
  - delete_clusters
  - deploy_clusters
  - E2E_testing
  - test

variables:
  CI_RUNNER_EXECUTOR: shell

build_server:
  stage: build_server
  script:
    - cd server
    - docker build -t cs590-final-group-5-server .
    - cd ..

build_ui:
  stage: build_ui
  script:
    - cd ui
    - docker build -t cs590-final-group-5-ui .
    - cd ..

delete_clusters:
  stage: delete_clusters
  script:
    - kubectl delete deployment db server ui --ignore-not-found
    - kubectl delete service db server ui --ignore-not-found

deploy:
  stage: deploy_clusters
  script:
    - kubectl create -f k8s/

testing: 
  stage: E2E_testing
  script: 
    - sleep 10
    - kubectl port-forward service/db 27017:27017 &
    - MONGO_PORT_FORWARD_PID=$!
    - curl http://localhost:31000

    - cd server
    - npm i
    - npm run setup
    - cd ..

    - npx playwright test --project=chromium --retries=0

    - kill $MONGO_PORT_FORWARD_PID


# testing2:
#   stage: test
#   script:
#     # - cd server
#     # - npm run setup
#     # - cd ..
#     - curl http://localhost:31000
#     - npx playwright test --project=webkit