apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: cs590-final-group-5-ui
        name: ui
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: ui
        env:
        - name: DISABLE_SECURITY
          value: "foo-bar-baz"
